# Read the documentation at https://bref.sh/docs/symfony/getting-started
service: symfony

# Set your team ID if you are using Bref Cloud
bref:
    team: demo-midi-formation

provider:
    name: aws
    region: us-east-1
    environment:
        APP_ENV: prod
        SQS_QUEUE_URL:
            Ref: DemoMidiFormationQueue
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - sqs:SendMessage
                  Resource:
                      Fn::GetAtt:
                          - DemoMidiFormationQueue
                          - Arn

plugins:
    - ./vendor/bref/bref

functions:

    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        runtime: php-84-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        runtime: php-84-console
        timeout: 120 # in seconds

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'

resources:
    Resources:
        DemoMidiFormationQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: demo-midi-formation-queue

    Outputs:
        DemoMidiFormationQueueUrl:
            Description: "URL of the SQS queue"
            Value:
                Ref: DemoMidiFormationQueue
