name: Deploy

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        concurrency: deploy-prod
        environment:
            name: prod
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    coverage: none
                    tools: bref/cli

            -   uses: ramsey/composer-install@v3
                with:
                    composer-options: '--optimize-autoloader --no-dev'

            -   name: Cache warmup
                run: APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup --no-interaction

            -   run: bref deploy --env=prod
                env:
                    BREF_TOKEN: ${{ secrets.BREF_TOKEN }}
